kind: Service
apiVersion: v1
metadata:
  name: {{ include "hydra.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hydra.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "hydra.chart" . }}
{{- if .Values.serviceLabels }}
{{ toYaml .Values.serviceLabels | indent 4 }}
{{- end }}
{{- if .Values.serviceAnnotations }}
  annotations:
{{ toYaml .Values.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "hydra.name" . }}
  ports:
    - name: public
      port: {{ .Values.service.publicPort }}
      targetPort: {{ .Values.service.publicPort }}
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: {{ .Values.service.adminPort }}
      protocol: TCP