dependencies:
- name: postgresql
  version: ^2.2.0
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: postgresql.enabled
- name: mariadb
  version: ^5.2.6
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: mariadb.enabled
